sudo: false
language: node_js
os:
  - windows
  - linux
node_js:
  - v6
  - v5
  - v4
addons:
  code_climate:
    repo_token: 837e8243c4d3917ce5dbdfd9f871acbbca441bcb121b65966f4b56dd76420df3
after_script:
  - npm install codeclimate-test-reporter
  - ./node_modules/.bin/codeclimate-test-reporter < ./coverage/lcov.info
